version: '3.4'

services:
  db:
    container_name: db_nest
    image: postgres:alpine
    environment:
      - POSTGRES_DB=nest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  db_test:
    container_name: db_nest_test
    image: postgres:alpine
    environment:
      - POSTGRES_DB=nest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5423:5432
